replicaCount: 1

image:
  repository: gmoulindan/prime-app
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 90

